### PR TITLE
Update randgraphs.jl

### PR DESCRIPTION
**Pull request by sbromberger**
I think this fixes a few inconsistencies.

### CODE REVIEW

**Comment by sbromberger** [comment]
I still think this PR ought to be reviewed - specifically, I'm not sure why we have the inner loop with `j` in `suitable()`.

**Comment by marcliberatore** [comment]
It should be iterating over all pairs of vertices, not just adjacent pairs – I will pull and update in a bit (maybe tomorrow?) and ask you to take another look. Thanks again for spending your time on this small thing.

**Comment by sbromberger** [comment]
Ah, I get it. There's probably a better way to do all-pairs iteration (check out `combinations`). ~~In any case, you weren't using `j` anywhere in the function, so~~ I was a bit confused. :)

I'm excited to merge this.

Edited: I don't know how I missed `s1, s2 = ends[i], ends[j]`. Sorry for mangling your code.

**Comment by marcliberatore** [comment]
No problem. I'll merge, unmangling if need be.

**Comment by marcliberatore** [comment]
But before I do, let me do some testing with `combinations` first to see what seems faster...

**Comment by marcliberatore** [comment]
Yup, `combinations` wins out. Merged in LightGraphs/pr/2.

**Pull request merged**
